package pojos;
// Generated May 21, 2016 2:50:29 PM by Hibernate Tools 4.3.1



/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private Integer adminId;
     private String adminUserName;
     private String adminPassword;

    public Admin() {
    }

    public Admin(String adminUserName, String adminPassword) {
       this.adminUserName = adminUserName;
       this.adminPassword = adminPassword;
    }
   
    public Integer getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }
    public String getAdminUserName() {
        return this.adminUserName;
    }
    
    public void setAdminUserName(String adminUserName) {
        this.adminUserName = adminUserName;
    }
    public String getAdminPassword() {
        return this.adminPassword;
    }
    
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword;
    }




}


