package pojos;
// Generated Jun 2, 2016 7:43:06 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name="admin"
    ,catalog="itiproject"
)
public class Admin  implements java.io.Serializable {


     private Integer adminId;
     private String adminUserName;
     private String adminPassword;
     private String adminToken;

    public Admin() {
    }

	
    public Admin(String adminUserName, String adminPassword) {
        this.adminUserName = adminUserName;
        this.adminPassword = adminPassword;
    }
    public Admin(String adminUserName, String adminPassword, String adminToken) {
       this.adminUserName = adminUserName;
       this.adminPassword = adminPassword;
       this.adminToken = adminToken;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="adminId", unique=true, nullable=false)
    public Integer getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    
    @Column(name="adminUserName", nullable=false)
    public String getAdminUserName() {
        return this.adminUserName;
    }
    
    public void setAdminUserName(String adminUserName) {
        this.adminUserName = adminUserName;
    }

    
    @Column(name="adminPassword", nullable=false, length=100)
    public String getAdminPassword() {
        return this.adminPassword;
    }
    
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword;
    }

    
    @Column(name="adminToken", length=100)
    public String getAdminToken() {
        return this.adminToken;
    }
    
    public void setAdminToken(String adminToken) {
        this.adminToken = adminToken;
    }




}


