package pojos;
// Generated May 19, 2016 3:27:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categorytable generated by hbm2java
 */
public class Categorytable  implements java.io.Serializable {


     private Integer categoryId;
     private String categoryName;
     private String imageOfCategoryUrl;
     private Set tagstables = new HashSet(0);
     private Set projectsforuserses = new HashSet(0);

    public Categorytable() {
    }

	
    public Categorytable(String categoryName, String imageOfCategoryUrl) {
        this.categoryName = categoryName;
        this.imageOfCategoryUrl = imageOfCategoryUrl;
    }
    public Categorytable(String categoryName, String imageOfCategoryUrl, Set tagstables, Set projectsforuserses) {
       this.categoryName = categoryName;
       this.imageOfCategoryUrl = imageOfCategoryUrl;
       this.tagstables = tagstables;
       this.projectsforuserses = projectsforuserses;
    }
   
    public Integer getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public String getImageOfCategoryUrl() {
        return this.imageOfCategoryUrl;
    }
    
    public void setImageOfCategoryUrl(String imageOfCategoryUrl) {
        this.imageOfCategoryUrl = imageOfCategoryUrl;
    }
    public Set getTagstables() {
        return this.tagstables;
    }
    
    public void setTagstables(Set tagstables) {
        this.tagstables = tagstables;
    }
    public Set getProjectsforuserses() {
        return this.projectsforuserses;
    }
    
    public void setProjectsforuserses(Set projectsforuserses) {
        this.projectsforuserses = projectsforuserses;
    }




}


