package pojos;
// Generated Jun 2, 2016 7:43:06 PM by Hibernate Tools 4.3.1

import com.google.gson.annotations.Expose;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Comments generated by hbm2java
 */
@Entity
@Table(name = "comments", catalog = "itiproject"
)
public class Comments implements java.io.Serializable {

    @Expose
    private Integer replyId;
    private Postforprojects postforprojects;
    @Expose
    private String comment;

    public Comments() {
    }

    public Comments(Postforprojects postforprojects, String comment) {
        this.postforprojects = postforprojects;
        this.comment = comment;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "replyId", unique = true, nullable = false)
    public Integer getReplyId() {
        return this.replyId;
    }

    public void setReplyId(Integer replyId) {
        this.replyId = replyId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "qId", nullable = false)
    public Postforprojects getPostforprojects() {
        return this.postforprojects;
    }

    public void setPostforprojects(Postforprojects postforprojects) {
        this.postforprojects = postforprojects;
    }

    @Column(name = "comment", nullable = false)
    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

}
