package pojos;
// Generated May 21, 2016 2:50:29 PM by Hibernate Tools 4.3.1



/**
 * DetailsId generated by hbm2java
 */
public class DetailsId  implements java.io.Serializable {


     private int porposerIdForDetails;
     private int projectIdForDetails;

    public DetailsId() {
    }

    public DetailsId(int porposerIdForDetails, int projectIdForDetails) {
       this.porposerIdForDetails = porposerIdForDetails;
       this.projectIdForDetails = projectIdForDetails;
    }
   
    public int getPorposerIdForDetails() {
        return this.porposerIdForDetails;
    }
    
    public void setPorposerIdForDetails(int porposerIdForDetails) {
        this.porposerIdForDetails = porposerIdForDetails;
    }
    public int getProjectIdForDetails() {
        return this.projectIdForDetails;
    }
    
    public void setProjectIdForDetails(int projectIdForDetails) {
        this.projectIdForDetails = projectIdForDetails;
    }




}


