package pojos;
// Generated May 21, 2016 2:50:29 PM by Hibernate Tools 4.3.1



/**
 * Details generated by hbm2java
 */
public class Details  implements java.io.Serializable {


     private DetailsId id;
     private Porposa porposa;
     private Projectsforusers projectsforusers;
     private String statusOfProjects;
     private int rateForOwner;
     private int rateForSuppliers;
     private String commentFromOwner;
     private String commentFromSuppliers;

    public Details() {
    }

    public Details(DetailsId id, Porposa porposa, Projectsforusers projectsforusers, String statusOfProjects, int rateForOwner, int rateForSuppliers, String commentFromOwner, String commentFromSuppliers) {
       this.id = id;
       this.porposa = porposa;
       this.projectsforusers = projectsforusers;
       this.statusOfProjects = statusOfProjects;
       this.rateForOwner = rateForOwner;
       this.rateForSuppliers = rateForSuppliers;
       this.commentFromOwner = commentFromOwner;
       this.commentFromSuppliers = commentFromSuppliers;
    }
   
    public DetailsId getId() {
        return this.id;
    }
    
    public void setId(DetailsId id) {
        this.id = id;
    }
    public Porposa getPorposa() {
        return this.porposa;
    }
    
    public void setPorposa(Porposa porposa) {
        this.porposa = porposa;
    }
    public Projectsforusers getProjectsforusers() {
        return this.projectsforusers;
    }
    
    public void setProjectsforusers(Projectsforusers projectsforusers) {
        this.projectsforusers = projectsforusers;
    }
    public String getStatusOfProjects() {
        return this.statusOfProjects;
    }
    
    public void setStatusOfProjects(String statusOfProjects) {
        this.statusOfProjects = statusOfProjects;
    }
    public int getRateForOwner() {
        return this.rateForOwner;
    }
    
    public void setRateForOwner(int rateForOwner) {
        this.rateForOwner = rateForOwner;
    }
    public int getRateForSuppliers() {
        return this.rateForSuppliers;
    }
    
    public void setRateForSuppliers(int rateForSuppliers) {
        this.rateForSuppliers = rateForSuppliers;
    }
    public String getCommentFromOwner() {
        return this.commentFromOwner;
    }
    
    public void setCommentFromOwner(String commentFromOwner) {
        this.commentFromOwner = commentFromOwner;
    }
    public String getCommentFromSuppliers() {
        return this.commentFromSuppliers;
    }
    
    public void setCommentFromSuppliers(String commentFromSuppliers) {
        this.commentFromSuppliers = commentFromSuppliers;
    }




}


