package pojos;
// Generated Jun 2, 2016 7:43:06 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetailsId generated by hbm2java
 */
@Embeddable
public class DetailsId  implements java.io.Serializable {


     private int porposerIdForDetails;
     private int projectIdForDetails;

    public DetailsId() {
    }

    public DetailsId(int porposerIdForDetails, int projectIdForDetails) {
       this.porposerIdForDetails = porposerIdForDetails;
       this.projectIdForDetails = projectIdForDetails;
    }
   


    @Column(name="porposerIdForDetails", nullable=false)
    public int getPorposerIdForDetails() {
        return this.porposerIdForDetails;
    }
    
    public void setPorposerIdForDetails(int porposerIdForDetails) {
        this.porposerIdForDetails = porposerIdForDetails;
    }


    @Column(name="projectIdForDetails", nullable=false)
    public int getProjectIdForDetails() {
        return this.projectIdForDetails;
    }
    
    public void setProjectIdForDetails(int projectIdForDetails) {
        this.projectIdForDetails = projectIdForDetails;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetailsId) ) return false;
		 DetailsId castOther = ( DetailsId ) other; 
         
		 return (this.getPorposerIdForDetails()==castOther.getPorposerIdForDetails())
 && (this.getProjectIdForDetails()==castOther.getProjectIdForDetails());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPorposerIdForDetails();
         result = 37 * result + this.getProjectIdForDetails();
         return result;
   }   


}


