package pojos;
// Generated Jun 2, 2016 7:43:06 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Details generated by hbm2java
 */
@Entity
@Table(name="details"
    ,catalog="itiproject"
)
public class Details  implements java.io.Serializable {


     private DetailsId id;
     private Porposa porposa;
     private Projectsforusers projectsforusers;
     private String statusOfProjects;
     private Integer rateForOwner;
     private Integer rateForSuppliers;
     private String commentFromOwner;
     private String commentFromSuppliers;

    public Details() {
    }

	
    public Details(DetailsId id, Porposa porposa, Projectsforusers projectsforusers, String statusOfProjects) {
        this.id = id;
        this.porposa = porposa;
        this.projectsforusers = projectsforusers;
        this.statusOfProjects = statusOfProjects;
    }
    public Details(DetailsId id, Porposa porposa, Projectsforusers projectsforusers, String statusOfProjects, Integer rateForOwner, Integer rateForSuppliers, String commentFromOwner, String commentFromSuppliers) {
       this.id = id;
       this.porposa = porposa;
       this.projectsforusers = projectsforusers;
       this.statusOfProjects = statusOfProjects;
       this.rateForOwner = rateForOwner;
       this.rateForSuppliers = rateForSuppliers;
       this.commentFromOwner = commentFromOwner;
       this.commentFromSuppliers = commentFromSuppliers;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="porposerIdForDetails", column=@Column(name="porposerIdForDetails", nullable=false) ), 
        @AttributeOverride(name="projectIdForDetails", column=@Column(name="projectIdForDetails", nullable=false) ) } )
    public DetailsId getId() {
        return this.id;
    }
    
    public void setId(DetailsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="porposerIdForDetails", nullable=false, insertable=false, updatable=false)
    public Porposa getPorposa() {
        return this.porposa;
    }
    
    public void setPorposa(Porposa porposa) {
        this.porposa = porposa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="projectIdForDetails", nullable=false, insertable=false, updatable=false)
    public Projectsforusers getProjectsforusers() {
        return this.projectsforusers;
    }
    
    public void setProjectsforusers(Projectsforusers projectsforusers) {
        this.projectsforusers = projectsforusers;
    }

    
    @Column(name="statusOfProjects", nullable=false, length=100)
    public String getStatusOfProjects() {
        return this.statusOfProjects;
    }
    
    public void setStatusOfProjects(String statusOfProjects) {
        this.statusOfProjects = statusOfProjects;
    }

    
    @Column(name="rateForOwner")
    public Integer getRateForOwner() {
        return this.rateForOwner;
    }
    
    public void setRateForOwner(Integer rateForOwner) {
        this.rateForOwner = rateForOwner;
    }

    
    @Column(name="rateForSuppliers")
    public Integer getRateForSuppliers() {
        return this.rateForSuppliers;
    }
    
    public void setRateForSuppliers(Integer rateForSuppliers) {
        this.rateForSuppliers = rateForSuppliers;
    }

    
    @Column(name="commentFromOwner")
    public String getCommentFromOwner() {
        return this.commentFromOwner;
    }
    
    public void setCommentFromOwner(String commentFromOwner) {
        this.commentFromOwner = commentFromOwner;
    }

    
    @Column(name="commentFromSuppliers")
    public String getCommentFromSuppliers() {
        return this.commentFromSuppliers;
    }
    
    public void setCommentFromSuppliers(String commentFromSuppliers) {
        this.commentFromSuppliers = commentFromSuppliers;
    }




}


