package pojos;
// Generated Jun 2, 2016 7:43:06 PM by Hibernate Tools 4.3.1

import com.google.gson.annotations.Expose;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Portofolioforuser generated by hbm2java
 */
@Entity
@Table(name = "portofolioforuser", catalog = "itiproject"
)
public class Portofolioforuser implements java.io.Serializable {

    @Expose
    private Integer portofolioId;
    
    private Category category;
 
    private Users users;
    @Expose
    private String portofolioDescription;
    @Expose
    private Set<Portofolioimages> portofolioimageses = new HashSet<Portofolioimages>(0);

    public Portofolioforuser() {
    }

    public Portofolioforuser(Users users, String portofolioDescription) {
        this.users = users;
        this.portofolioDescription = portofolioDescription;
    }

    public Portofolioforuser(Category category, Users users, String portofolioDescription, Set<Portofolioimages> portofolioimageses) {
        this.category = category;
        this.users = users;
        this.portofolioDescription = portofolioDescription;
        this.portofolioimageses = portofolioimageses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "portofolioId", unique = true, nullable = false)
    public Integer getPortofolioId() {
        return this.portofolioId;
    }

    public void setPortofolioId(Integer portofolioId) {
        this.portofolioId = portofolioId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "categroyIdOfPortofolio")
    public Category getCategory() {
        return this.category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "userIdPortf", nullable = false)
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @Column(name = "portofolioDescription", nullable = false)
    public String getPortofolioDescription() {
        return this.portofolioDescription;
    }

    public void setPortofolioDescription(String portofolioDescription) {
        this.portofolioDescription = portofolioDescription;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "portofolioforuser")
    public Set<Portofolioimages> getPortofolioimageses() {
        return this.portofolioimageses;
    }

    public void setPortofolioimageses(Set<Portofolioimages> portofolioimageses) {
        this.portofolioimageses = portofolioimageses;
    }

}
