package pojos;
// Generated May 19, 2016 3:27:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Portofolioforuser generated by hbm2java
 */
public class Portofolioforuser  implements java.io.Serializable {


     private Integer portofolioId;
     private Users users;
     private String portofolioDescription;
     private Set portofolioiamgeses = new HashSet(0);

    public Portofolioforuser() {
    }

	
    public Portofolioforuser(Users users, String portofolioDescription) {
        this.users = users;
        this.portofolioDescription = portofolioDescription;
    }
    public Portofolioforuser(Users users, String portofolioDescription, Set portofolioiamgeses) {
       this.users = users;
       this.portofolioDescription = portofolioDescription;
       this.portofolioiamgeses = portofolioiamgeses;
    }
   
    public Integer getPortofolioId() {
        return this.portofolioId;
    }
    
    public void setPortofolioId(Integer portofolioId) {
        this.portofolioId = portofolioId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getPortofolioDescription() {
        return this.portofolioDescription;
    }
    
    public void setPortofolioDescription(String portofolioDescription) {
        this.portofolioDescription = portofolioDescription;
    }
    public Set getPortofolioiamgeses() {
        return this.portofolioiamgeses;
    }
    
    public void setPortofolioiamgeses(Set portofolioiamgeses) {
        this.portofolioiamgeses = portofolioiamgeses;
    }




}


