package pojos;
// Generated Jun 2, 2016 7:43:06 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Portofolioimages generated by hbm2java
 */
@Entity
@Table(name = "portofolioimages", catalog = "itiproject"
)
public class Portofolioimages implements java.io.Serializable {

    private Integer imageId;
    private Portofolioforuser portofolioforuser;
    private String portfolioImageUrl;

    public Portofolioimages() {
    }

    public Portofolioimages(Portofolioforuser portofolioforuser, String portfolioImageUrl) {
        this.portofolioforuser = portofolioforuser;
        this.portfolioImageUrl = portfolioImageUrl;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "imageId", unique = true, nullable = false)
    public Integer getImageId() {
        return this.imageId;
    }

    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "protofolioId", nullable = false)
    public Portofolioforuser getPortofolioforuser() {
        return this.portofolioforuser;
    }

    public void setPortofolioforuser(Portofolioforuser portofolioforuser) {
        this.portofolioforuser = portofolioforuser;
    }

    @Column(name = "PortfolioImageURL", nullable = false, length = 100)
    public String getPortfolioImageUrl() {
        return this.portfolioImageUrl;
    }

    public void setPortfolioImageUrl(String portfolioImageUrl) {
        this.portfolioImageUrl = portfolioImageUrl;
    }

}
