package pojos;
// Generated May 21, 2016 12:50:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Postforprojects generated by hbm2java
 */
public class Postforprojects  implements java.io.Serializable {


     private Integer qid;
     private Projectsforusers projectsforusers;
     private Users users;
     private String post;
     private Set commentses = new HashSet(0);

    public Postforprojects() {
    }

	
    public Postforprojects(Projectsforusers projectsforusers, Users users, String post) {
        this.projectsforusers = projectsforusers;
        this.users = users;
        this.post = post;
    }
    public Postforprojects(Projectsforusers projectsforusers, Users users, String post, Set commentses) {
       this.projectsforusers = projectsforusers;
       this.users = users;
       this.post = post;
       this.commentses = commentses;
    }
   
    public Integer getQid() {
        return this.qid;
    }
    
    public void setQid(Integer qid) {
        this.qid = qid;
    }
    public Projectsforusers getProjectsforusers() {
        return this.projectsforusers;
    }
    
    public void setProjectsforusers(Projectsforusers projectsforusers) {
        this.projectsforusers = projectsforusers;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getPost() {
        return this.post;
    }
    
    public void setPost(String post) {
        this.post = post;
    }
    public Set getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set commentses) {
        this.commentses = commentses;
    }




}


