package pojos;
// Generated May 19, 2016 3:27:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Postforprojects generated by hbm2java
 */
public class Postforprojects  implements java.io.Serializable {


     private Integer qid;
     private Projectsforusers projectsforusers;
     private Users users;
     private String post;
     private Set skilltables = new HashSet(0);
     private Set replyings = new HashSet(0);

    public Postforprojects() {
    }

	
    public Postforprojects(Projectsforusers projectsforusers, Users users, String post) {
        this.projectsforusers = projectsforusers;
        this.users = users;
        this.post = post;
    }
    public Postforprojects(Projectsforusers projectsforusers, Users users, String post, Set skilltables, Set replyings) {
       this.projectsforusers = projectsforusers;
       this.users = users;
       this.post = post;
       this.skilltables = skilltables;
       this.replyings = replyings;
    }
   
    public Integer getQid() {
        return this.qid;
    }
    
    public void setQid(Integer qid) {
        this.qid = qid;
    }
    public Projectsforusers getProjectsforusers() {
        return this.projectsforusers;
    }
    
    public void setProjectsforusers(Projectsforusers projectsforusers) {
        this.projectsforusers = projectsforusers;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getPost() {
        return this.post;
    }
    
    public void setPost(String post) {
        this.post = post;
    }
    public Set getSkilltables() {
        return this.skilltables;
    }
    
    public void setSkilltables(Set skilltables) {
        this.skilltables = skilltables;
    }
    public Set getReplyings() {
        return this.replyings;
    }
    
    public void setReplyings(Set replyings) {
        this.replyings = replyings;
    }




}


