package pojos;
// Generated Jun 2, 2016 7:43:06 PM by Hibernate Tools 4.3.1

import com.google.gson.annotations.Expose;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Projectsimages generated by hbm2java
 */
@Entity
@Table(name = "projectsimages", catalog = "itiproject"
)
public class Projectsimages implements java.io.Serializable {

    @Expose
    private Integer imageId;
    private Projectsforusers projectsforusers;
    @Expose
    private String imageUrl;

    public Projectsimages() {
    }

    public Projectsimages(Projectsforusers projectsforusers, String imageUrl) {
        this.projectsforusers = projectsforusers;
        this.imageUrl = imageUrl;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "imageId", unique = true, nullable = false)
    public Integer getImageId() {
        return this.imageId;
    }

    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "projectId", nullable = false)
    public Projectsforusers getProjectsforusers() {
        return this.projectsforusers;
    }

    public void setProjectsforusers(Projectsforusers projectsforusers) {
        this.projectsforusers = projectsforusers;
    }

    @Column(name = "imageURL", nullable = false, length = 100)
    public String getImageUrl() {
        return this.imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

}
