package pojos;
// Generated May 19, 2016 3:27:38 PM by Hibernate Tools 4.3.1



/**
 * Replying generated by hbm2java
 */
public class Replying  implements java.io.Serializable {


     private Integer replyId;
     private Postforprojects postforprojects;
     private String comment;

    public Replying() {
    }

    public Replying(Postforprojects postforprojects, String comment) {
       this.postforprojects = postforprojects;
       this.comment = comment;
    }
   
    public Integer getReplyId() {
        return this.replyId;
    }
    
    public void setReplyId(Integer replyId) {
        this.replyId = replyId;
    }
    public Postforprojects getPostforprojects() {
        return this.postforprojects;
    }
    
    public void setPostforprojects(Postforprojects postforprojects) {
        this.postforprojects = postforprojects;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


