package pojos;
// Generated Jun 2, 2016 7:43:06 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Skilltable generated by hbm2java
 */
@Entity
@Table(name = "skilltable", catalog = "itiproject"
)
public class Skilltable implements java.io.Serializable {

    private Integer skillId;
    private String skillName;
    private Set<Users> userses = new HashSet<Users>(0);
    private Set<Projectsforusers> projectsforuserses = new HashSet<Projectsforusers>(0);

    public Skilltable() {
    }

    public Skilltable(String skillName) {
        this.skillName = skillName;
    }

    public Skilltable(String skillName, Set<Users> userses, Set<Projectsforusers> projectsforuserses) {
        this.skillName = skillName;
        this.userses = userses;
        this.projectsforuserses = projectsforuserses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "skillId", unique = true, nullable = false)
    public Integer getSkillId() {
        return this.skillId;
    }

    public void setSkillId(Integer skillId) {
        this.skillId = skillId;
    }

    @Column(name = "skillName", nullable = false, length = 155)
    public String getSkillName() {
        return this.skillName;
    }

    public void setSkillName(String skillName) {
        this.skillName = skillName;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "skillsofuser", catalog = "itiproject", joinColumns = {
        @JoinColumn(name = "skillId", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "userIdForSkill", nullable = false, updatable = false)})
    public Set<Users> getUserses() {
        return this.userses;
    }

    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }

    @ManyToMany(fetch = FetchType.LAZY, mappedBy = "skilltables")
    public Set<Projectsforusers> getProjectsforuserses() {
        return this.projectsforuserses;
    }

    public void setProjectsforuserses(Set<Projectsforusers> projectsforuserses) {
        this.projectsforuserses = projectsforuserses;
    }

}
