package pojos;
// Generated May 21, 2016 2:50:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Skilltable generated by hbm2java
 */
public class Skilltable  implements java.io.Serializable {


     private Integer skillId;
     private String skillName;
     private Set userses = new HashSet(0);
     private Set projectsforuserses = new HashSet(0);

    public Skilltable() {
    }

	
    public Skilltable(String skillName) {
        this.skillName = skillName;
    }
    public Skilltable(String skillName, Set userses, Set projectsforuserses) {
       this.skillName = skillName;
       this.userses = userses;
       this.projectsforuserses = projectsforuserses;
    }
   
    public Integer getSkillId() {
        return this.skillId;
    }
    
    public void setSkillId(Integer skillId) {
        this.skillId = skillId;
    }
    public String getSkillName() {
        return this.skillName;
    }
    
    public void setSkillName(String skillName) {
        this.skillName = skillName;
    }
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }
    public Set getProjectsforuserses() {
        return this.projectsforuserses;
    }
    
    
    public void setProjectsforuserses(Set projectsforuserses) {
        this.projectsforuserses = projectsforuserses;
    }




}


