package pojos;
// Generated Jun 2, 2016 7:43:06 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SocialAccounts generated by hbm2java
 */
@Entity
@Table(name="social_accounts"
    ,catalog="itiproject"
)
public class SocialAccounts  implements java.io.Serializable {


     private Integer socialAccountId;
     private Users users;
     private String providerUserId;
     private String provider;
     private Date createdAt;
     private Date updatedAt;

    public SocialAccounts() {
    }

    public SocialAccounts(Users users, String providerUserId, String provider, Date createdAt, Date updatedAt) {
       this.users = users;
       this.providerUserId = providerUserId;
       this.provider = provider;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="social_account_id", unique=true, nullable=false)
    public Integer getSocialAccountId() {
        return this.socialAccountId;
    }
    
    public void setSocialAccountId(Integer socialAccountId) {
        this.socialAccountId = socialAccountId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="provider_user_id", nullable=false)
    public String getProviderUserId() {
        return this.providerUserId;
    }
    
    public void setProviderUserId(String providerUserId) {
        this.providerUserId = providerUserId;
    }

    
    @Column(name="provider", nullable=false)
    public String getProvider() {
        return this.provider;
    }
    
    public void setProvider(String provider) {
        this.provider = provider;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }




}


