package pojos;
// Generated May 19, 2016 3:27:38 PM by Hibernate Tools 4.3.1



/**
 * Tagsofprojects generated by hbm2java
 */
public class Tagsofprojects  implements java.io.Serializable {


     private int tagId;
     private Projectsforusers projectsforusers;
     private Tagstable tagstable;

    public Tagsofprojects() {
    }

    public Tagsofprojects(Projectsforusers projectsforusers, Tagstable tagstable) {
       this.projectsforusers = projectsforusers;
       this.tagstable = tagstable;
    }
   
    public int getTagId() {
        return this.tagId;
    }
    
    public void setTagId(int tagId) {
        this.tagId = tagId;
    }
    public Projectsforusers getProjectsforusers() {
        return this.projectsforusers;
    }
    
    public void setProjectsforusers(Projectsforusers projectsforusers) {
        this.projectsforusers = projectsforusers;
    }
    public Tagstable getTagstable() {
        return this.tagstable;
    }
    
    public void setTagstable(Tagstable tagstable) {
        this.tagstable = tagstable;
    }




}


