package pojos;
// Generated May 21, 2016 2:50:29 PM by Hibernate Tools 4.3.1



/**
 * Tagstable generated by hbm2java
 */
public class Tagstable  implements java.io.Serializable {


     private Integer tagId;
     private Categorytable categorytable;
     private String tagDescription;
     private Tagsofprojects tagsofprojects;

    public Tagstable() {
    }

	
    public Tagstable(Categorytable categorytable, String tagDescription) {
        this.categorytable = categorytable;
        this.tagDescription = tagDescription;
    }
    public Tagstable(Categorytable categorytable, String tagDescription, Tagsofprojects tagsofprojects) {
       this.categorytable = categorytable;
       this.tagDescription = tagDescription;
       this.tagsofprojects = tagsofprojects;
    }
   
    public Integer getTagId() {
        return this.tagId;
    }
    
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }
    public Categorytable getCategorytable() {
        return this.categorytable;
    }
    
    public void setCategorytable(Categorytable categorytable) {
        this.categorytable = categorytable;
    }
    public String getTagDescription() {
        return this.tagDescription;
    }
    
    public void setTagDescription(String tagDescription) {
        this.tagDescription = tagDescription;
    }
    public Tagsofprojects getTagsofprojects() {
        return this.tagsofprojects;
    }
    
    public void setTagsofprojects(Tagsofprojects tagsofprojects) {
        this.tagsofprojects = tagsofprojects;
    }




}


