package pojos;
// Generated Jun 2, 2016 7:43:06 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Tags generated by hbm2java
 */
@Entity
@Table(name = "tags", catalog = "itiproject"
)
public class Tags implements java.io.Serializable {

    private Integer tagId;
    private Category category;
    private String tagDescription;
    private Tagsofprojects tagsofprojects;

    public Tags() {
    }

    public Tags(String tagDescription) {
        this.tagDescription = tagDescription;
    }

    public Tags(Category category, String tagDescription, Tagsofprojects tagsofprojects) {
        this.category = category;
        this.tagDescription = tagDescription;
        this.tagsofprojects = tagsofprojects;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "tagId", unique = true, nullable = false)
    public Integer getTagId() {
        return this.tagId;
    }

    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "categoryId")
    public Category getCategory() {
        return this.category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    @Column(name = "tagDescription", nullable = false)
    public String getTagDescription() {
        return this.tagDescription;
    }

    public void setTagDescription(String tagDescription) {
        this.tagDescription = tagDescription;
    }

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "tags")
    public Tagsofprojects getTagsofprojects() {
        return this.tagsofprojects;
    }

    public void setTagsofprojects(Tagsofprojects tagsofprojects) {
        this.tagsofprojects = tagsofprojects;
    }

}
