package pojos;
// Generated Jun 2, 2016 7:43:06 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Tagsofprojects generated by hbm2java
 */
@Entity
@Table(name="tagsofprojects"
    ,catalog="itiproject"
)
public class Tagsofprojects  implements java.io.Serializable {


     private int tagId;
     private Projectsforusers projectsforusers;
     private Tags tags;

    public Tagsofprojects() {
    }

    public Tagsofprojects(Projectsforusers projectsforusers, Tags tags) {
       this.projectsforusers = projectsforusers;
       this.tags = tags;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="tags"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="tagId", unique=true, nullable=false)
    public int getTagId() {
        return this.tagId;
    }
    
    public void setTagId(int tagId) {
        this.tagId = tagId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="projectId", nullable=false)
    public Projectsforusers getProjectsforusers() {
        return this.projectsforusers;
    }
    
    public void setProjectsforusers(Projectsforusers projectsforusers) {
        this.projectsforusers = projectsforusers;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Tags getTags() {
        return this.tags;
    }
    
    public void setTags(Tags tags) {
        this.tags = tags;
    }




}


