package pojos;
// Generated May 21, 2016 2:50:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer userId;
     private String userEmail;
     private String userImageUrl;
     private String password;
     private boolean gender;
     private String userName;
     private int ped;
     private String country;
     private String governorate;
     private String city;
     private String street;
     private String summery;
     private String professinalTiltle;
     private String identefire;
     private Set phoneofusers = new HashSet(0);
     private Set portofolioforusers = new HashSet(0);
     private Set projectsforuserses = new HashSet(0);
     private Set porposas = new HashSet(0);
     private Set postforprojectses = new HashSet(0);
     private Set skilltables = new HashSet(0);

    public Users() {
    }

	
    public Users(String userEmail, String userImageUrl, String password, boolean gender, String userName, int ped, String country, String governorate, String city, String professinalTiltle, String identefire) {
        this.userEmail = userEmail;
        this.userImageUrl = userImageUrl;
        this.password = password;
        this.gender = gender;
        this.userName = userName;
        this.ped = ped;
        this.country = country;
        this.governorate = governorate;
        this.city = city;
        this.professinalTiltle = professinalTiltle;
        this.identefire = identefire;
    }
    public Users(String userEmail, String userImageUrl, String password, boolean gender, String userName, int ped, String country, String governorate, String city, String street, String summery, String professinalTiltle, String identefire, Set phoneofusers, Set portofolioforusers, Set projectsforuserses, Set porposas, Set postforprojectses, Set skilltables) {
       this.userEmail = userEmail;
       this.userImageUrl = userImageUrl;
       this.password = password;
       this.gender = gender;
       this.userName = userName;
       this.ped = ped;
       this.country = country;
       this.governorate = governorate;
       this.city = city;
       this.street = street;
       this.summery = summery;
       this.professinalTiltle = professinalTiltle;
       this.identefire = identefire;
       this.phoneofusers = phoneofusers;
       this.portofolioforusers = portofolioforusers;
       this.projectsforuserses = projectsforuserses;
       this.porposas = porposas;
       this.postforprojectses = postforprojectses;
       this.skilltables = skilltables;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public String getUserImageUrl() {
        return this.userImageUrl;
    }
    
    public void setUserImageUrl(String userImageUrl) {
        this.userImageUrl = userImageUrl;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isGender() {
        return this.gender;
    }
    
    public void setGender(boolean gender) {
        this.gender = gender;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public int getPed() {
        return this.ped;
    }
    
    public void setPed(int ped) {
        this.ped = ped;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getGovernorate() {
        return this.governorate;
    }
    
    public void setGovernorate(String governorate) {
        this.governorate = governorate;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getSummery() {
        return this.summery;
    }
    
    public void setSummery(String summery) {
        this.summery = summery;
    }
    public String getProfessinalTiltle() {
        return this.professinalTiltle;
    }
    
    public void setProfessinalTiltle(String professinalTiltle) {
        this.professinalTiltle = professinalTiltle;
    }
    public String getIdentefire() {
        return this.identefire;
    }
    
    public void setIdentefire(String identefire) {
        this.identefire = identefire;
    }
    public Set getPhoneofusers() {
        return this.phoneofusers;
    }
    
    public void setPhoneofusers(Set phoneofusers) {
        this.phoneofusers = phoneofusers;
    }
    public Set getPortofolioforusers() {
        return this.portofolioforusers;
    }
    
    public void setPortofolioforusers(Set portofolioforusers) {
        this.portofolioforusers = portofolioforusers;
    }
    public Set getProjectsforuserses() {
        return this.projectsforuserses;
    }
    
    public void setProjectsforuserses(Set projectsforuserses) {
        this.projectsforuserses = projectsforuserses;
    }
    public Set getPorposas() {
        return this.porposas;
    }
    
    public void setPorposas(Set porposas) {
        this.porposas = porposas;
    }
    public Set getPostforprojectses() {
        return this.postforprojectses;
    }
    
    public void setPostforprojectses(Set postforprojectses) {
        this.postforprojectses = postforprojectses;
    }
    public Set getSkilltables() {
        return this.skilltables;
    }
    
    public void setSkilltables(Set skilltables) {
        this.skilltables = skilltables;
    }




}


